dataset:
  name: 'cifar10'

autoaug:
  model:
    type: 'wresnet40_2'
  loader:
    aug: 'fa_reduced_cifar10'
    cutout: 16
    batch: 512
    epochs: 200
  lr_schedule:
    type: 'cosine'
    warmup:
      multiplier: 4
      epochs: 5
  optimizer:
    lr: 0.1
    type: 'sgd'
    nesterov: True
    decay: 0.0002